@startuml
'https://plantuml.com/class-diagram







class DGS {
    - name
    - vatnumber

}

class SNS {
    - String name
    - String vatNumber

}
class EMPLOYEE {
-Name
-Code
}
class ADMIN {
-Role
-Name
-code
}
class RECEPTIONIST {
-Role
-Name
-code

}

class NURSE {
   -name
   -Role
   -code


}
class SNSUSER {

- name
- citizenCardNumber
- snsUserNumber

}
class VACCINATIONCENTER {
-name

}
class HEALTHCARECENTER {
-name

}

class VACCINEAPPOINTMENT {
- date
- time

}
class VACCINE {
-Id
-Name

}
class VACCINETYPE{
 -Code
}
class VACCINATION{
 -Code
}



DGS "1" --> "*" SNS
SNS "1" --> "*" EMPLOYEE
SNS "1" --> "*" SNSUSER
EMPLOYEE  "1" --> "0.1" RECEPTIONIST
EMPLOYEE  "1" --> "0.1" NURSE
EMPLOYEE  "1" --> "0.1" ADMIN
SNS "1" --> "0.1" VACCINATIONCENTER
SNS "1" --> "0.1" HEALTHCARECENTER
NURSE "1" --> "*" VACCINATION
RECEPTIONIST"0,1" --> "*" VACCINEAPPOINTMENT
VACCINEAPPOINTMENT"*" --> "1" VACCINETYPE
VACCINE"*" --> "1" VACCINETYPE
VACCINE"*" --> "1" VACCINATION
SNSUSER"1" --> "*" VACCINATION
@enduml