@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

SNS "1" --> "*" EMPLOYEE






class DGS {
    - names
    -vatnumber
     size()
}

class SNS {
  - String name
    - String vatNumber
    - String website
    - String phone
    - String email

    - addTask(task)
    - validateTask(task)
    + anyEmployeeHasEmail(email)
    + Organization(name, vatNumber, webSite, phone, email, postalAddress, manager)
    + createTask(reference, description, informalDesccription,\ntechnicalDescription, duration, cost, taskCategoryDescription)
    - getEmployeeByEmail(email)

}
class EMPLOYEE {
Object[] elementData
size()
}
class ADMIN {
Object[] elementData
size()
}
class RECEPTIONIST {
Object[] elementData
size()
}
class NURSE {
Object[] elementData
size()
}
class SNSUSER {
Object[] elementData
size()
}
class VACCINATIONCENTER {
Object[] elementData
size()
}
class HEALTHCARECENTER {
Object[] elementData
size()
}
class VACCINATION {
Object[] elementData
size()
}
class VACCINEAPPOINTMENT {
Object[] elementData
size()
}
class VACCINE {
Id
Name
Brand
Vaccine Type
}
class VACCINETYPE{
 Code
 Short description
 Vaccine technology
}
class VACCINEAPPOINTMENT {
Object[] elementData
size()
}
class ADVERSEREACTIONS {
Object[] elementData
size()
}
class ARRIVAL{
Object[] elementData
size()
}
class RECOVERYROOM{
Object[] elementData
size()
}
class WAITING {
Object[] elementData
size()
}
class PANDEMIC {
Object[] elementData
size()
}
class ApplicationSession{
Object[] elementData
size()
}
class UserSession {
Object[] elementData
size()
}
enum TimeUnit {
HOURS
MINUTES
SECONDS
}

enum Date {
DAYS
MONTH
YEAR
}

@enduml